"""initial schema

Revision ID: 04341be9b35c
Revises:
Create Date: 2026-08-18 15:07:27.837835
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "04341be9b35c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "EDITOR", name="admin_role", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_epoch", sa.String(length=36), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user")),
    )
    op.create_index(op.f("ix_admin_user_email"), "admin_user", ["email"], unique=True)
    op.create_table(
        "access_code",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "INITIAL",
                "SCHEDULED",
                "MANUAL",
                name="rotation_reason",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("scan_count", sa.Integer(), nullable=False),
        sa.Column("rotated_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rotated_by_admin_id"],
            ["admin_user.id"],
            name=op.f("fk_access_code_rotated_by_admin_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_code")),
        sa.UniqueConstraint("code", name="uq_access_code_code"),
    )
    op.create_index(op.f("ix_access_code_code"), "access_code", ["code"], unique=False)
    op.create_index(op.f("ix_access_code_is_active"), "access_code", ["is_active"], unique=False)
    op.create_table(
        "access_policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auto_rotate", sa.Boolean(), nullable=False),
        sa.Column("rotation_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("guest_session_minutes", sa.Integer(), nullable=False),
        sa.Column("revoke_sessions_on_rotation", sa.Boolean(), nullable=False),
        sa.Column("max_active_sessions", sa.Integer(), nullable=False),
        sa.Column("updated_by_admin_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "guest_session_minutes BETWEEN 5 AND 43200", name=op.f("ck_access_policy_session_range")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_access_policy_singleton")),
        sa.CheckConstraint(
            "rotation_interval_minutes BETWEEN 5 AND 525600",
            name=op.f("ck_access_policy_rotation_range"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_id"],
            ["admin_user.id"],
            name=op.f("fk_access_policy_updated_by_admin_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_policy")),
    )
    op.create_table(
        "attraction",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "HERITAGE",
                "WINE",
                "NATURE",
                "GASTRONOMY",
                "FAMILY",
                name="attraction_category",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("name_fr", sa.String(length=160), nullable=False),
        sa.Column("name_en", sa.String(length=160), nullable=False),
        sa.Column("summary_fr", sa.String(length=400), nullable=False),
        sa.Column("summary_en", sa.String(length=400), nullable=False),
        sa.Column("description_fr", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("travel_time_min", sa.Integer(), nullable=True),
        sa.Column("website_url", sa.String(length=400), nullable=True),
        sa.Column("image_path", sa.String(length=200), nullable=True),
        sa.Column("image_credit", sa.String(length=300), nullable=True),
        sa.Column("updated_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_id"],
            ["admin_user.id"],
            name=op.f("fk_attraction_updated_by_admin_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attraction")),
    )
    op.create_index(op.f("ix_attraction_category"), "attraction", ["category"], unique=False)
    op.create_index(op.f("ix_attraction_slug"), "attraction", ["slug"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("actor_admin_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_hash", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_admin_id"],
            ["admin_user.id"],
            name=op.f("fk_audit_log_actor_admin_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_actor_admin_id"), "audit_log", ["actor_admin_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "guide_section",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ARRIVAL",
                "HOUSE",
                "PRACTICAL",
                "RULES",
                "LOCAL_TIPS",
                name="guide_category",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "GUEST", name="visibility", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("title_fr", sa.String(length=160), nullable=False),
        sa.Column("title_en", sa.String(length=160), nullable=False),
        sa.Column("body_fr", sa.Text(), nullable=False),
        sa.Column("body_en", sa.Text(), nullable=False),
        sa.Column("updated_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_id"],
            ["admin_user.id"],
            name=op.f("fk_guide_section_updated_by_admin_id_admin_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guide_section")),
    )
    op.create_index(op.f("ix_guide_section_slug"), "guide_section", ["slug"], unique=True)
    op.create_index(
        op.f("ix_guide_section_visibility"), "guide_section", ["visibility"], unique=False
    )
    op.create_table(
        "guest_session",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("access_code_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_hash", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["access_code_id"],
            ["access_code.id"],
            name=op.f("fk_guest_session_access_code_id_access_code"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_session")),
    )
    op.create_index(
        op.f("ix_guest_session_expires_at"), "guest_session", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_guest_session_token_hash"), "guest_session", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guest_session_token_hash"), table_name="guest_session")
    op.drop_index(op.f("ix_guest_session_expires_at"), table_name="guest_session")
    op.drop_table("guest_session")
    op.drop_index(op.f("ix_guide_section_visibility"), table_name="guide_section")
    op.drop_index(op.f("ix_guide_section_slug"), table_name="guide_section")
    op.drop_table("guide_section")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_admin_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_attraction_slug"), table_name="attraction")
    op.drop_index(op.f("ix_attraction_category"), table_name="attraction")
    op.drop_table("attraction")
    op.drop_table("access_policy")
    op.drop_index(op.f("ix_access_code_is_active"), table_name="access_code")
    op.drop_index(op.f("ix_access_code_code"), table_name="access_code")
    op.drop_table("access_code")
    op.drop_index(op.f("ix_admin_user_email"), table_name="admin_user")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
